# Generated by Django 3.2.7 on 2021-09-27 14:34

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, verbose_name='Criado')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('type', models.CharField(max_length=150, verbose_name='tipo')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('status', models.CharField(choices=[('A', 'Analisado'), ('N', 'Não analisado')], max_length=15, verbose_name='status')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
            ],
        ),
    ]
