# Generated by Django 3.2.7 on 2021-09-30 23:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('imagem', models.ImageField(upload_to=core.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=150)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Analisado'), ('N', 'Não analisado')], max_length=15)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='core.imagem')),
            ],
        ),
    ]
